<a href="https://colab.research.google.com/github/Jasper-Hewitt/Wind_project/blob/main/distilBert_semantic_search.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

source: https://github.com/dreji18/Semantic-Search-using-DistilBert/blob/main/Semantic%20Search%20using%20Distilbert.ipynb

In [2]:
!pip install sentence_transformers
import os
import numpy as np
import pandas as pd

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
model = SentenceTransformer('distilbert-base-nli-stsb-mean-tokens')

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 KB 4.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.8/5.8 MB 81.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 80.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 182.4/182.4 KB 20.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 121.9 MB/s eta 0:00:00
  Created wheel for sentence_transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125938 sha256=7a84c4762710bad31e42ad05fe79536903584f7d8cd59266a1a1c8016d8fffb6
  Stored in directory: /root/.cache/pip/wheels/5e/6f/8c/d88aec621f3f542d26fac0342bef5e693335d125f4e54aeffe
Successfully built sentence_transformers


Downloading:   0%|          | 0.00/345 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/190 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/4.01k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/555 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/122 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/265M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/466k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/505 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/229 [00:00<?, ?B/s]

In [6]:
import pandas as pd
!wget https://github.com/dreji18/Semantic-Search-using-DistilBert/blob/main/Marvel%20Datastore.xlsx?raw=true

--2023-01-13 06:58:25--  https://github.com/dreji18/Semantic-Search-using-DistilBert/blob/main/Marvel%20Datastore.xlsx?raw=true
Resolving github.com (github.com)... 192.30.255.113
Connecting to github.com (github.com)|192.30.255.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/dreji18/Semantic-Search-using-DistilBert/raw/main/Marvel%20Datastore.xlsx [following]
--2023-01-13 06:58:25--  https://github.com/dreji18/Semantic-Search-using-DistilBert/raw/main/Marvel%20Datastore.xlsx
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/dreji18/Semantic-Search-using-DistilBert/main/Marvel%20Datastore.xlsx [following]
--2023-01-13 06:58:25--  https://raw.githubusercontent.com/dreji18/Semantic-Search-using-DistilBert/main/Marvel%20Datastore.xlsx
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.109.

In [7]:
df = pd.read_excel('/content/Marvel Datastore.xlsx?raw=true')
df.head()

Sentences
0  Thor Odinson is the Asgardian God of Thunder, ...
1  Upon being welcomed back to Asgard as a hero, ...
2  Thor returned to Asgard having defeated his br...
3  Loki Laufeyson was the biological son of Laufe...
4  Transported by the wormhole to Sanctuary, Loki...

In [8]:
def find_similar(vector_representation, all_representations, k=1):
    similarity_matrix = cosine_similarity(vector_representation, all_representations)
    #np.fill_diagonal(similarity_matrix, 0)
    similarities = similarity_matrix[0]
    if k == 1:
        return [np.argmax(similarities)]
    elif k is not None:
        return np.flip(similarities.argsort()[-k:][::1])

In [9]:
paragraph = df.iloc[:, 0] # the first column values
embeddings_distilbert = model.encode(paragraph.values)

In [10]:
embeddings_distilbert[0]

array([-3.18955407e-02,  2.64471054e-01, -1.94422707e-01, -4.75514203e-01,
       -1.09503470e-01, -2.53094941e-01,  5.96421063e-01, -4.50715959e-01,
        1.68840617e-01, -3.64453703e-01, -8.98364186e-02,  7.02318490e-01,
       -2.97972679e-01,  6.37583017e-01, -1.55584350e-01, -2.64987290e-01,
        5.77679649e-03,  2.48432532e-01, -5.53226352e-01,  2.96144634e-01,
       -4.08101529e-01,  6.04276210e-02, -3.62437546e-01,  3.10531020e-01,
        1.45208001e-01, -5.95851898e-01, -1.39671504e-01, -2.07188874e-01,
        4.42511976e-01,  7.60546327e-01,  3.11907291e-01,  1.27536565e-01,
       -1.53978974e-01, -3.31967145e-01, -8.09909701e-02,  5.71737111e-01,
       -6.53036058e-01, -3.07104558e-01,  6.25130236e-01,  7.10621998e-02,
        1.19132705e-01,  3.89192812e-02,  3.48347604e-01,  1.02812164e-01,
       -1.90297455e-01, -3.84668708e-01,  5.81478067e-02, -4.34741229e-01,
       -6.66364431e-02,  2.11260468e-01, -2.52673268e-01, -8.37571383e-01,
       -5.99107146e-03, -

In [11]:

embeddings_distilbert[0].shape

(768,)

In [12]:
def find_similar(vector_representation, all_representations, k=1):
    similarity_matrix = cosine_similarity(vector_representation, all_representations)
    #np.fill_diagonal(similarity_matrix, 0)
    similarities = similarity_matrix[0]
    if k == 1:
        return [np.argmax(similarities)]
    elif k is not None:
        return np.flip(similarities.argsort()[-k:][::1])

In [13]:
paragraph = df.iloc[:, 0] # the first column values
embeddings_distilbert = model.encode(paragraph.values)

In [14]:
embeddings_distilbert[0]

array([-3.18955407e-02,  2.64471054e-01, -1.94422707e-01, -4.75514203e-01,
       -1.09503470e-01, -2.53094941e-01,  5.96421063e-01, -4.50715959e-01,
        1.68840617e-01, -3.64453703e-01, -8.98364186e-02,  7.02318490e-01,
       -2.97972679e-01,  6.37583017e-01, -1.55584350e-01, -2.64987290e-01,
        5.77679649e-03,  2.48432532e-01, -5.53226352e-01,  2.96144634e-01,
       -4.08101529e-01,  6.04276210e-02, -3.62437546e-01,  3.10531020e-01,
        1.45208001e-01, -5.95851898e-01, -1.39671504e-01, -2.07188874e-01,
        4.42511976e-01,  7.60546327e-01,  3.11907291e-01,  1.27536565e-01,
       -1.53978974e-01, -3.31967145e-01, -8.09909701e-02,  5.71737111e-01,
       -6.53036058e-01, -3.07104558e-01,  6.25130236e-01,  7.10621998e-02,
        1.19132705e-01,  3.89192812e-02,  3.48347604e-01,  1.02812164e-01,
       -1.90297455e-01, -3.84668708e-01,  5.81478067e-02, -4.34741229e-01,
       -6.66364431e-02,  2.11260468e-01, -2.52673268e-01, -8.37571383e-01,
       -5.99107146e-03, -

In [15]:

embeddings_distilbert[0].shape

(768,)

In [16]:
search_string = "thor's weapon"
search_vect = model.encode([search_string])

In [17]:

search_vect[0].shape

(768,)

In [18]:
K = 3 # no. of paragraphs that has to be extracted
distilbert_similar_indexes = find_similar(search_vect, embeddings_distilbert, K)

In [19]:

distilbert_similar_indexes

array([7, 6, 1])

In [20]:
output_data = []
for index in distilbert_similar_indexes:
    output_data.append(paragraph[index])

In [23]:
output_data#[0]

['Stormbreaker is an enchanted axe used by Thor. It was forged from Uru on Nidavellir, and can summon the Bifrost.',
 'Mjølnir ("that which smashes")[1] was a powerful enchanted war-hammer forged by the Dwarves for the Asgardian Royal Family. The hammer was destroyed by Hela during a confrontation between her, Thor and Loki in 2017.\n\nFollowing the Snap, Thor time traveled to 2013 and brought the past version of the hammer into 2023, where it was primarily used by Captain America during the Battle of Earth. Following Thanos\' death, Captain America traveled back in time to Asgard of 2013 in order to return Mjølnir.',
 "Upon being welcomed back to Asgard as a hero, Thor was forced to return to Earth in order to retrieve Loki after he had survived to fall through a black hole and had begun his attempt at world domination, having taken possession of the Tesseract. Thor joined the Avengers under the guidance of S.H.I.E.L.D. and stood with them to stop the schemes of his own adopted brothe